# Generated by Django 5.1.2 on 2024-11-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_remove_assignment_questions_assigmentquestion_and_more"),
        ("questions", "0004_questionessayanswer_questionfillblankanswer_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssigmentQuestion",
            new_name="AssignmentQuestion",
        ),
    ]
