# Generated by Django 5.1.2 on 2024-11-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_rename_assigmentquestion_assignmentquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentessayanswer",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="assignmentfillblankanswer",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="assignmentmultianswer",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
