# Generated by Django 5.1.2 on 2024-10-29 08:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
        ("token_blacklist", "0012_alter_outstandingtoken_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="token_blacklist.outstandingtoken",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["token", "timestamp"],
                        name="authorizati_token_i_d80fdf_idx",
                    )
                ],
            },
        ),
    ]
