# Generated by Django 5.1.2 on 2024-10-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuser",
            table="users",
        ),
    ]
