# Generated by Django 5.1.2 on 2024-10-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_test_num_essay_question_test_num_fill_bank_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="description",
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name="test",
            name="num_essay_question",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="test",
            name="num_fill_bank_question",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="test",
            name="num_multiple_answer_question",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="test",
            name="num_multiple_choice_question",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
