# Generated by Django 5.1.2 on 2024-10-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_rename_limit_question_test_use_all_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="num_fill_bank_question",
            new_name="num_fill_blank_question",
        ),
    ]
